#ifndef _SIGS_
#define _SIGS_

enum SIGS {

    SIG_EXIT,
    SIG_CURSOR_UP,
    SIG_CURSOR_DOWN,
    SIG_CURSOR_LEFT,
    SIG_CURSOR_RIGHT,
    SIG_OFFSET_PANEL_UP,
    SIG_OFFSET_PANEL_DOWN,
    SIG_OFFSET_PANEL_LEFT,
    SIG_OFFSET_PANEL_RIGHT,
    SIG_CHANGE_WORKDIR_UP,
    SIG_CHANGE_WORKDIR_DOWN,
    
    SIG_REFRESH_CURSOR,
    SIG_CLOSE_PANEL,
    SIG_REFRESH_SCREEN,
    SIG_CHANGE_PANEL,
    SIG_ERROR,
    SIG_RESIZE_WIN,
    SIG_VER_SEPARATION,
    SIG_HOR_SEPARATION,
    
    END_SIGS
};

#endif
