#ifndef _SIGS_
#define _SIGS_

enum SIGNAL {

    EXIT,
    CURSOR_UP,
    CURSOR_DOWN,
    CURSOR_LEFT,
    CURSOR_RIGHT,
    OFFSET_PANEL_UP,
    OFFSET_PANEL_DOWN,
    OFFSET_PANEL_LEFT,
    OFFSET_PANEL_RIGHT,
    REFRESH_CURSOR,
    CLOSE_PANEL,
    REFRESH_SCREEN,
    CHANGE_PANEL,
    ERROR,
    RESIZE_WIN,
    VER_SEPARATION,
    HOR_SEPARATION,
    MOVE_BUFFER,

    SETTINGS_MODE,
    NORMAL_MODE,
    EDIT_ITEM_UP,
    EDIT_ITEM_DOWN,
    SAVE_SETTINGS,

    CHANGE_WORKDIR_UP,
    CHANGE_WORKDIR_DOWN,
    
    END
};

#endif
